"""add department

Revision ID: 676a4f748e55
Revises: 5a5c7bc04eaa
Create Date: 2024-07-04 00:52:59.169188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676a4f748e55'
down_revision = '5a5c7bc04eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
